export default {
    "en": {
        "rarFound": "Rar archive found, extracting...",
        "rarProgress": "Extracting: ",
        "rarError": "Error extracting .rar file: ",
        "rarDone": "Extraction done!",
        "deleteFileSuccess": "File deleted: ",
        "deleteFileError": "Could not delete file: ",
        "deleteDirectorySuccess": "Directory deleted: ",
        "deleteDirectoryError": "Could not delete directory: ",
        "posterNotFound": "No poster found",
        "posterDownloaded": "Poster downloaded",
        "posterCouldNotLoadAPI": "Could not load poster API: ",
        "itemRenameSuccess": "Item renamed: ",
        "itemRenameError": "Could not rename item: ",
        "createDirectorySuccess": "Directory created: ",
        "createDirectoryError": "Could not create directory: ",
        "filesScannedError": "Could not scan files: ",
        "movieProcessSuccess": "Movie done processing: ",
        "fsStatError": "Could not get FS.STAT info: ",
        "writeToFileError": "Could not write to file: ",
        "createDirectoryForFileSuccess": "Created directory: ",
        "createDirectoryForFileError": "Could not create directory: "
    },
    "no": {
        "rarFound": "Rar arkiv funnet, pakker ut...",
        "rarProgress": "Pakker ut: ",
        "rarError": "Kunne ikke pakke ut fil: ",
        "rarDone": "Utpakking av fil ferdig!",
        "deleteFileSuccess": "Filen ble slettet: ",
        "deleteFileError": "Kunne ikke slette fil: ",
        "deleteDirectorySuccess": "Mappen ble slettet: ",
        "deleteDirectoryError": "Kunne ikke slette mappe: ",
        "posterNotFound": "Fant ikke poster",
        "posterDownloaded": "Poster lastet ned",
        "posterCouldNotLoadAPI": "Kunne ikke laste poster API: ",
        "itemRenameSuccess": "Endret navn på fil: ",
        "itemRenameError": "Kunne ikke endre navn på fil: ",
        "createDirectorySuccess": "Mappe opprettet: ",
        "createDirectoryError": "Kunne ikke opprette mappe: ",
        "filesScannedError": "Kunne ikke skanne filer: ",
        "movieProcessSuccess": "Film ferdig organisert: ",
        "fsStatError": "Kunne ikke hente FS.STAT info: ",
        "writeToFileError": "Kunne ikke skrive til fil: ",
        "createDirectoryForFileSuccess": "Mappe opprettet: ",
        "createDirectoryForFileError": "Kunne ikke oppprette mappe for: "
    }
}